/** Curated public portfolio. Bilingual pairs are [English, 简体中文].
 * Source: owner-approved master CV, 2026-09-11; repository evidence is linked.
 * Public descriptions do not grant access to private code or disclose runtime data.
 */
export const pair = (en, zh) => [en, zh];
export const person = {
  name: 'Rongze Gao', chinese: '高荣泽', email: 'rgao28@jh.edu',
  site: 'https://rongzegao.com', github: 'https://github.com/zeron-G',
  linkedin: 'https://www.linkedin.com/in/rongze-gao-09b488303/',
  professor: 'https://carey.jhu.edu/faculty/faculty-directory/gordon-gao-phd',
  lab: 'https://cdhai.carey.jhu.edu/ai-agent-lab/', updated: '2026-09-11',
  about: pair(
    'I am a Johns Hopkins graduate building at the intersection of AI agents, healthcare research and physical systems. At CDHAI, I work with Professor Gordon Gao on patient-data analysis and personalized forecasting. Outside the lab, I build persistent agent runtimes and cross-language infrastructure, and support U.S.-market robotics projects at Tuskrobots.',
    '我是高荣泽，约翰斯·霍普金斯大学信息系统与人工智能硕士。在 CDHAI 跟随 Gordon Gao 教授研究患者数据分析与个体化预测；在实验室之外，开发持续运行的智能体和跨语言基础组件，并以实习、兼职形式支持塔斯克机器人美国市场项目。'),
  philosophy: pair('Models are only one part of the system. I care about how data enters, how tools act, how failures recover, and how results can be checked.', '模型只是系统的一部分。我同样关心数据怎样进入系统、工具怎样执行、失败怎样恢复，以及结果能否被独立验证。')
};
const repo = name => `https://github.com/zeron-G/${name}`;
export const projects = [
  {id:'anima-family', name:'ANIMA / ANIMA²', category:'agents', number:'01', private:true, featured:true,
    type:pair('Persistent agent runtime','持续运行的智能体系统'), status:pair('Independent development · Demonstrable','独立开发 · 可演示'),
    headline:pair('Beyond a conversation.\nA continuous system.','不止一次对话。\n而是持续运行的系统。'),
    summary:pair('Memory, tool execution and multi-machine collaboration, designed as one traceable runtime—not another chat interface.','把记忆、工具执行与多机协作组织成可追溯的运行时，而不只是另一个聊天界面。'),
    stack:['Python async','React / TypeScript','SQLite WAL','SSH'], links:[['ANIMA',repo('anima')],['ANIMA²',repo('anima2')],['Verification',repo('anima2')+'/blob/main/specs/001-anima2/verification.md']],
    problem:pair('How can an agent keep working across sessions, interfaces and machines without losing state or hiding failed actions? The first ANIMA explored modular memory and distributed nodes; ANIMA² reimplemented the runtime around explicit lifecycle and execution contracts.','怎样让智能体跨会话、跨界面、跨设备持续工作，而不丢失状态、不掩盖失败？第一代 ANIMA 探索模块化记忆与分布式节点；ANIMA² 以明确的生命周期和执行契约重新实现运行时。'),
    build:[
      pair('Built an asynchronous Python kernel shared by React Web and Textual terminal clients. Persisted sessions, sourced memories, execution events and artifacts in SQLite WAL.','以异步 Python 内核统一 React Web 与 Textual 终端入口，用 SQLite WAL 持久化会话、带来源的记忆、执行事件和产物。'),
      pair('Loaded tools on demand and archived large outputs as hashed artifacts. Added paginated retrieval and exact-evidence lookup so long tasks can recover original material after context compression.','按需加载工具，把大结果归档为带哈希的产物；加入分页检索与精确证据回查，让长任务在上下文压缩后仍能找回原始材料。'),
      pair('Implemented approvals, revocation, atomic writes with hash preconditions and process-tree cancellation. Plugins pass subprocess contract tests before versioned activation or rollback; the kernel is not self-modified.','实现执行审批、权限撤销、带哈希前置条件的原子写入与进程树取消；插件通过进程级契约测试后才能版本化激活或回滚，不修改内核。'),
      pair('Built SSH node discovery, parallel delegation, artifact return and explicit memory-sync conflict resolution. Verified a coordinator and two model workers across Windows and Linux.','实现 SSH 节点发现、并行任务委派、产物回传与显式记忆同步冲突处理；验证 Windows 与 Linux 上协调者和两个模型工作节点的协作。')],
    evidence:pair('The September 9 acceptance ledger records code repair checked against untouched tests, real browser form submission, memory correction/forgetting, reconnect recovery and cross-machine execution. Recorded suites: 216 Python tests, 30 Web unit tests and 15 browser scenarios. These are project records, not a fresh benchmark run on this website.','9 月 9 日验收记录覆盖未修改测试下的代码修复、真实浏览器表单提交、记忆纠错与遗忘、断线恢复和跨机执行。记录包含 216 项 Python 测试、30 项 Web 单元测试及 15 项浏览器场景；这些是项目验收记录，不是本网站重新运行的基准。'),
    boundary:pair('Private source; walkthroughs available. Engineering acceptance is not a claim of SWE-bench superiority, an OS security sandbox or proven multi-month companionship.','源码私有，可进行项目演示。工程验收不等于 SWE-bench 排名、操作系统级安全沙箱或长期陪伴效果验证。')},
  {id:'synapse',name:'Synapse',category:'systems',number:'02',featured:true,private:false,
    type:pair('Cross-language infrastructure','跨语言系统基础组件'),status:pair('Library, bindings & test tooling','通信库、语言绑定与测试工具'),
    headline:pair('Different languages.\nShared understanding.','不同语言。\n同一份数据契约。'),
    summary:pair('A Rust shared-memory bridge connecting Python intelligence with native C++ / Rust applications, with one schema and explicit process lifecycles.','以 Rust 共享内存连接 Python AI 与 C++ / Rust 原生应用，用统一 schema 和明确的进程生命周期管理数据交换。'),
    stack:['Rust','Python / C++','Shared memory','.bridge IDL'],links:[['Repository',repo('Synapse')],['Benchmarks',repo('Synapse')+'/blob/main/benchmarks/README.md']],
    problem:pair('AI processes and native applications often need to exchange typed state without sharing a process or maintaining incompatible message definitions. Synapse makes the memory layout, communication channel and shutdown contract explicit.','AI 进程与原生应用需要交换类型化状态，但不应该被迫共享进程或分别维护不一致的消息定义。Synapse 将内存布局、通信通道与退出契约显式化。'),
    build:[
      pair('Implemented a Rust shared-memory core and bidirectional single-producer/single-consumer ring buffers. Wrapped Linux POSIX memory and Windows file mappings; exposed Python native/mmap and C++ header-only access.','实现 Rust 共享内存核心与双向单生产者／单消费者环形缓冲区；封装 Linux POSIX 共享内存和 Windows 文件映射，提供 Python 原生／mmap 路径与 C++ 头文件接口。'),
      pair('Built the .bridge lexer, parser, AST and C ABI layout calculator. Generated Rust structures, Python ctypes and C++ definitions with layout assertions from one schema.','实现 .bridge 词法分析、语法解析、AST 与 C ABI 布局计算；从单一 schema 生成 Rust 结构体、Python ctypes 和带布局断言的 C++ 定义。'),
      pair('Added typed channels, channel registration and seqlock latest-value slots for asynchronous inference. Implemented configurable spin/yield/park waiting, heartbeats, peer-death detection and graceful shutdown.','加入类型化通道、通道注册表与用于异步推理的 seqlock 最新值槽；实现自旋／让出／阻塞等待、心跳、对端退出检测与优雅关闭。')],
    evidence:pair('Deliverables include round-trip, type-layout and failure-path tests, Python-sender / C++-receiver examples and Criterion benchmark entry points.','交付通信往返、类型布局和异常路径测试，Python 发送／C++ 接收示例，以及 Criterion 基准入口。'),
    boundary:pair('No hardware-independent latency or speedup is claimed. Same-process microbenchmarks and cross-process measurements must be interpreted separately; SPSC is not a general multi-producer queue.','不宣称脱离硬件与负载条件的延迟或加速倍数。同进程微基准与跨进程测量需要区分；SPSC 也不等于任意多生产者队列。')},
  {id:'hapf',name:'HAPF',category:'health',number:'03',featured:true,private:false,
    type:pair('Patient-adaptive forecasting','个体化患者时序预测'),status:pair('CDHAI · Research prototype','CDHAI · 研究原型'),
    headline:pair('Shared knowledge.\nPersonal predictions.','共享群体规律。\n理解个体差异。'),
    summary:pair('Population learning, low-rank patient adaptation and uncertainty calibration for glucose forecasting—with a fallback when personalization is not supported.','将群体学习、患者低秩适配与不确定性校准用于血糖预测；当个人证据不足时，保留群体模型回退。'),
    stack:['Causal TCN','Patient adaptation','Conformal calibration','CGM'],links:[['Repository',repo('CDHAI-HAPF')],['Protocol & results',repo('CDHAI-HAPF')+'/blob/main/docs/proof_of_concept.md']],
    problem:pair('An independent model for every patient wastes shared information, while a single population model can miss individual differences. HAPF investigates bounded personalization for 30- and 60-minute glucose forecasting.','为每位患者独立训练模型会浪费共享信息，单一群体模型又可能忽略个体差异。HAPF 探索受约束的个体化，用于未来 30 与 60 分钟血糖预测。'),
    build:[
      pair('Built a causal TCN and patient-conditioned low-rank adapter, with shrinkage and early stopping rather than full per-patient model copies.','构建因果 TCN 与患者条件化低秩适配器，使用收缩与早停，而不是为每位患者复制完整模型。'),
      pair('Split by real subject identity rather than record ID. Separated adaptation, calibration and testing chronologically; normalization uses training subjects only.','按真实受试者而非记录 ID 划分样本；按时间隔离适配、校准与测试，归一化仅使用训练受试者数据。'),
      pair('Implemented probabilistic forecast heads, chronological conformal calibration and a gate that selects personalization or population fallback using calibration evidence.','实现概率预测头、时序保形校准和选择门控，根据校准证据决定启用个体化或回退群体预测。')],
    evidence:pair('Exploratory leave-one-subject-out evaluation covered 12 CGM subjects. The recorded 30/60-minute RMSE was 18.492/29.696 mg/dL for gated selection, versus 18.724/30.674 for the population TCN; personalization was accepted in 6 of 12 folds.','探索性留一验证覆盖 12 名 CGM 受试者。记录中的门控模型 30/60 分钟 RMSE 为 18.492/29.696 mg/dL，群体 TCN 为 18.724/30.674；12 折中 6 折采用个体化。'),
    boundary:pair('Small exploratory sample; the 60-minute patient-level uncertainty interval crossed zero. Preclinical research only—not diagnosis, insulin dosing or proven clinical benefit.','样本较小，60 分钟患者级差异的区间跨越零。仅为临床前研究，不用于诊断、胰岛素剂量决策，也不代表已证明的临床收益。')},
  {id:'patient-data-agent',name:'CDHAI_June',category:'health',private:false,
    type:pair('Evidence-first research agent','证据优先的患者研究智能体'),status:pair('Research workbench','研究工作台'),
    summary:pair('Statistics and model checks first. An evidence ledger, reusable artifacts and grounded reports second.','先统计计算与模型检查，再以证据台账、可复用产物生成有依据的研究报告。'),stack:['Python','CGM','Workflow orchestration'],links:[['Repository',repo('CDHAI_June')]],
    problem:pair('Fluent medical prose should not replace computation. This workflow separates deterministic patient-data analysis from hypothesis generation and narrative reporting.','流畅的医学文本不应替代计算。本流程将确定性患者数据分析与假设生成、报告写作分离。'),
    build:[pair('Normalized CSV, Excel, JSON and Parquet patient files; detected time/glucose/event fields and produced missingness profiles, CGM metrics, prediction baselines and figures.','统一 CSV、Excel、JSON、Parquet 患者文件，识别时间／血糖／事件字段，生成缺失值概览、CGM 指标、预测基线与图表。'),pair('Orchestrated bounded hypothesis–test–evidence–report cycles using allowlisted analysis functions. Persisted patient knowledge and cached HAPF training/results for later cycles.','用允许执行的分析函数编排有界的“假设—检验—证据—报告”循环；持久化患者研究知识，并缓存 HAPF 训练与结果供后续轮次复用。')],
    evidence:pair('Repository includes data-composite builders, structured evidence outputs and Ubuntu/Windows test, smoke-pipeline and package-build workflows.','仓库包含组合数据构建器、结构化证据产物及 Ubuntu／Windows 测试、冒烟流程与构建工作流。'),boundary:pair('Research tooling associated with HAI-Agent work, not the whole HAI-Agent platform or a clinical decision product.','这是与 HAI-Agent 工作相关的研究实现，不等同于整个平台或临床决策产品。')},
  {id:'vta',name:'Virtual Teaching Assistant',category:'agents',private:true,
    type:pair('From requirements to a teaching pilot','从教学需求到学院试点'),status:pair('Carey teaching pilot','Carey 学院教学试点'),summary:pair('An independently developed teaching-support application brought into an institutional pilot.','独立开发教学辅助应用，并进入学院真实教学试点。'),stack:['Agent application','Product delivery'],links:[['AI Agent Lab',person.lab]],
    problem:pair('Translate instructional requirements into a working virtual assistant rather than a stand-alone model demonstration.','将教学需求转化为可运行的虚拟助教，而不只是独立的模型演示。'),build:[pair('Independently owned application development from instructional needs to a functioning teaching-support system.','独立承担应用开发，将教学需求落地为可运行的教学辅助系统。'),pair('Delivered the application for a teaching pilot at Johns Hopkins Carey Business School.','交付应用并进入约翰斯·霍普金斯大学 Carey 商学院教学试点。')],evidence:pair('Pilot status and sole-development responsibility are confirmed in the owner-provided career record.','个人履历已确认独立开发责任与学院试点状态。'),boundary:pair('School-wide deployment, user counts and learning-effectiveness gains are not claimed.','不宣称全校部署、未确认的用户规模或学习效果提升。')},
  {id:'pidog',name:'PiDog / embodied-robot',category:'robotics',private:true,
    type:pair('Voice-to-motion embodied interaction','语音到动作的具身交互'),status:pair('Hardware prototype','硬件交互原型'),summary:pair('Layered control, voice, telemetry and remote AI on Raspberry Pi and an existing quadruped platform.','在树莓派与现有机器狗平台上连接分层控制、语音、遥测和远端 AI。'),stack:['Raspberry Pi','FastAPI','WebSocket','Voice'],links:[['PiDog',repo('pidog-eva')],['Firmware',repo('embodied-robot')]],
    problem:pair('Connect high-level AI interaction to physical actions while separating device execution from heavier model and speech services.','将高层 AI 交互连接到物理动作，同时区分设备执行与算力较重的模型、语音服务。'),build:[pair('Organized hardware primitives, motion state transitions, autonomous behavior and HTTP/WebSocket interfaces into four layers on SunFounder PiDog.','在 SunFounder PiDog 上组织硬件原语、运动状态转换、自主行为和 HTTP／WebSocket 接口四层软件。'),pair('Integrated wake-word detection, speech recognition/synthesis, a Web console and bounded IMU-based head compensation; consolidated device APIs into embodied-robot.','整合唤醒词、语音识别／合成、Web 控制台和受限 IMU 头部姿态补偿；将设备接口整理至 embodied-robot。')],evidence:pair('Device-side implementation, motion state machine and integration documentation are available for demonstration.','可展示设备端实现、运动状态机与系统集成文档。'),boundary:pair('Existing hardware and SDK; head compensation is not full-body balance. Migration and interface authentication review remain outstanding.','复用现有硬件与 SDK；头部补偿不是全身平衡控制。迁移与接口鉴权审查仍待完成。')},
  {id:'mech',name:'mech / 身外化身',category:'robotics',private:false,
    type:pair('Powered-exoskeleton research planning','主动外骨骼技术预研'),status:pair('Planning & architecture','方案与架构阶段'),summary:pair('A staged architecture for sensing, assistance and safety boundaries in wearable robotics.','为可穿戴机器人梳理传感、助力与安全边界的分阶段架构。'),stack:['Wearables','Sensor architecture','Safety planning'],links:[['Repository',repo('mech')]],
    problem:pair('Translate a wearable-robot concept into a staged, testable plan without putting language-model decisions inside motor safety loops.','将可穿戴机器人概念拆为分阶段可验证方案，不把语言模型决策放入电机安全控制环。'),build:[pair('Documented system architecture, phase-one hardware/sensor choices, resource needs, risks and bench-to-prototype validation steps.','形成系统架构、一期硬件／传感选型、资源需求、风险与从台架到原型的验证路线。'),pair('Separated ANIMA-level memory/planning from device control; mapped the different roles of IMU, foot pressure, joint feedback and EMG.','分离 ANIMA 上层记忆／规划与设备控制，梳理 IMU、足压、关节反馈和肌电的不同用途。')],evidence:pair('Technical planning documents and phase-one kickoff package are public.','技术方案与一期启动计划公开可读。'),boundary:pair('Planning-stage deliverables, not a validated wearable prototype or medical device.','交付物属于规划预研，不是已验证的可穿戴样机或医疗器械。')},
  {id:'kinsoul',name:'Kinsoul / SoulPack',category:'agents',private:true,
    type:pair('Persistent personas & portable state','持续人格与可迁移状态'),status:pair('Product prototype / format draft','产品原型／格式草案'),summary:pair('A memory-aware conversational application and a draft format for transferring agent state.','具有记忆的对话产品，以及用于迁移智能体状态的格式草案。'),stack:['FastAPI','React','State modeling','JSON Schema'],links:[['Kinsoul',repo('kinsoul')],['SoulPack',repo('soulpack')]],
    problem:pair('Keep persona, memory and application state manageable across sessions and eventually across runtimes.','让人格、记忆与应用状态能够跨会话管理，并探索跨运行环境迁移。'),build:[pair('Connected durable turns, relationship-scoped memories, layered prompt compilation and SSE chat to a React/FastAPI application, with import/export and account workflows.','将持久化对话、关系范围记忆、分层提示词编译与 SSE 聊天连接到 React／FastAPI 应用，支持导入导出和账户流程。'),pair('Designed SoulPack carriers, event/version semantics, schemas and a Python validation core, distinguishing immutable logs from versioned state and derived caches.','设计 SoulPack 载体、事件／版本语义、schema 与 Python 校验核心，区分不可变日志、版本化状态和派生缓存。')],evidence:pair('Application deployment/test records and draft specification/reference validation code exist in the repositories.','仓库中包含应用部署／测试记录、格式草案与参考校验代码。'),boundary:pair('Not an industry-adopted standard or evidence of recurring revenue. Product metering and full merge/conformance coverage are unfinished.','不是已被行业采纳的标准，也不代表稳定收入；产品计量与完整合并／一致性覆盖仍未完成。')},
  {id:'alpha-agent',name:'Alpha Research Agent',category:'agents',private:false,
    type:pair('Traceable quantitative research','可追溯的量化研究自动化'),status:pair('Research tooling','研究工具'),summary:pair('A planner-driven loop for factor exploration, simulation, robustness checks and governed submission.','以规划驱动因子探索、仿真、稳健性检查与受控提交的研究循环。'),stack:['Python','Planning','Streamlit','Evaluation'],links:[['Repository',repo('worldquant-alpha-research-agent')]],
    problem:pair('Make quantitative exploration inspectable, not a collection of cherry-picked backtests.','让量化探索过程可检查，而不是仅展示挑选出来的回测。'),build:[pair('Implemented explore/exploit/robustness/harvest stages, structured planner decisions and correlation-aware candidate repair.','实现探索、利用、稳健性与收获四阶段流程、结构化规划决策及相关性感知的候选修复。'),pair('Added simulation/check clients, disabled-by-default submission, manual approval, JSON run histories and a same-budget baseline evaluation harness.','接入仿真／检查客户端，默认禁用提交，提供人工审批、JSON 运行记录及同预算基线评估框架。')],evidence:pair('CLI, Streamlit console, replay cases and research logs are documented in the public repository.','公开仓库提供 CLI、Streamlit 控制台、回放案例与研究日志说明。'),boundary:pair('Research automation is not live-trading performance or a WorldQuant endorsement.','研究自动化不等于实盘收益或 WorldQuant 背书。')},
  {id:'finrag',name:'FinRAG Agent',category:'agents',private:false,
    type:pair('Source-grounded financial retrieval','有来源的财务文档检索'),status:pair('JHU course-team project','JHU 课程团队项目'),summary:pair('Section-aware retrieval and streaming answers over SEC 10-K filings with source tracing.','围绕 SEC 10-K 文件实现章节感知检索、流式回答和引用追踪。'),stack:['FAISS','MMR','FastAPI','RAG'],links:[['Team repository',repo('FinRAG-Agent')]],
    problem:pair('Answer questions over long company filings while preserving the source context for financial claims.','回答长篇公司文件中的问题，同时保留财务判断的原文上下文。'),build:[pair('The team combined section detection and fine/coarse document chunks, expanding precise retrieval hits into context using company/section metadata and FAISS/MMR.','团队组合章节识别与细／粗粒度分块，通过公司／章节元数据及 FAISS／MMR 从精确命中扩展到上下文。'),pair('Integrated provider adapters, conversational memory and FastAPI/SSE answers with a browser source panel across Alphabet, Amazon and Microsoft filings.','整合模型提供方、对话记忆和 FastAPI／SSE 回答，在浏览器展示 Alphabet、Amazon、Microsoft 文件的来源。')],evidence:pair('Public course-team repository and documented retrieval/application workflow.','公开课程团队仓库与检索／应用流程文档。'),boundary:pair('A team deliverable; individual ownership of every module is not claimed.','团队交付，不将每个模块都归为个人独立开发。')},
  {id:'inventory-rl',name:'Adaptive Inventory RL',category:'experiments',private:false,
    type:pair('Inventory & pricing simulation','库存与定价模拟'),status:pair('Course research / simulation','课程研究／模拟实验'),summary:pair('Studying inventory and price decisions with tabular reinforcement learning in a retail simulator.','在零售模拟器中用表格型强化学习研究库存与定价决策。'),stack:['Reinforcement learning','Simulation','Policy evaluation'],links:[['Repository',repo('adaptive-inventory-pricing-rl')]],
    problem:pair('Explore sequential inventory and pricing decisions under demand uncertainty within an explicit simulation.','在明确的模拟环境中探索不确定需求下的连续库存与定价决策。'),build:[pair('Developed the simulation/research setup for adaptive inventory and pricing, comparing learned decision policies with reference policies.','构建自适应库存与定价的模拟研究设置，将学习到的决策策略与参考策略比较。')],evidence:pair('Project code and experiment context are available in the linked repository.','项目代码与实验背景见链接仓库。'),boundary:pair('Simulator results are not actual retail revenue, cost savings or deployment evidence.','模拟结果不是实际零售收入、成本节省或部署证据。')},
  {id:'blackhole',name:'Black Hole Renderer',category:'experiments',private:false,
    type:pair('Scientific computing meets visual craft','科学计算与视觉表达'),status:pair('Personal visualization project','个人可视化项目'),summary:pair('A Schwarzschild renderer exploring null-geodesic ray tracing, lensing and an accretion disk.','以 Schwarzschild 时空为基础，探索零测地线光线追踪、引力透镜与吸积盘渲染。'),stack:['Python','Numerical methods','WebGL'],links:[['Repository',repo('blackhole-sim')]],
    problem:pair('Turn a mathematical model of curved light paths into a comprehensible visual experiment.','把弯曲光路的数学模型转化为可理解的视觉实验。'),build:[pair('Built a Python Schwarzschild black-hole renderer with null-geodesic ray tracing and an accretion-disk model, plus a real-time WebGL version.','开发基于零测地线追踪与吸积盘模型的 Python Schwarzschild 黑洞渲染器，并制作实时 WebGL 版本。')],evidence:pair('Source implementation and rendering experiments are available in the repository.','仓库提供源码实现与渲染实验。'),boundary:pair('Scientific visualization, not a claim of original astrophysical discovery.','属于科学可视化，不宣称原创天体物理发现。')}
];
export const experience = [
 {id:'cdhai',years:'2026.01 — Present',title:pair('Johns Hopkins · CDHAI','约翰斯·霍普金斯大学 · CDHAI'),role:pair('Research Assistant · Professor Gordon Gao','研究助理 · Gordon Gao 教授'),link:person.lab,
  text:pair('Develop patient-adaptive forecasting and evidence-first analysis workflows. Independently delivered the Virtual Teaching Assistant piloted at Carey; additional contributions include Ospr.ai agents and AI-glasses embedded development.','开展患者个体化预测与证据优先的数据分析工作流研究；独立交付进入 Carey 试点的虚拟助教，另参与 Ospr.ai 智能体与 AI 眼镜嵌入式相关研发。')},
 {id:'tusk',years:'2025.02 — Present',title:pair('Tuskrobots','塔斯克机器人'),role:pair('Engineering intern / part-time engineer · U.S. market','工程师（实习／兼职）· 美国市场'),link:null,
  text:pair('Connect presales application planning with robot deployment, commissioning and ongoing U.S.-market project maintenance. Troubleshoot software–device integration and real-world operating issues. The period combines internship and part-time engagement.','衔接售前方案、设备部署与调试，以实习及兼职形式持续维护美国市场项目；排查软件与设备联调及实际运行问题。该任期不代表全程全职。')},
 {id:'ward',years:'2025.09 — 2026.01',title:pair('Vital Guardian · Ward Infinity','Vital Guardian · Ward Infinity'),role:pair('AI Specialist · Team awarded $20,000','AI 专家 · 团队获 20,000 美元最高奖'),link:'https://carey.jhu.edu/news/ward-infinity-makes-path-tech-minded-entrepreneurs-improve-public-health',
  text:pair('Built device-connected kidney-health monitoring agents and ML tools for prediction and risk analysis. Supported the venture’s AI development; contributed to the Ward Infinity top-prize team.','构建设备连接的肾脏健康监测智能体及预测、风险分析 ML 工具，支持团队 AI 开发与转型，参与团队获得 Ward Infinity 最高奖。')},
 {id:'worldquant',years:'Part-time / Remote',title:pair('WorldQuant BRAIN','WorldQuant BRAIN'),role:pair('Research Consultant','研究顾问'),link:repo('worldquant-alpha-research-agent'),text:pair('Research alpha factors and signals from historical data, evaluating factor behavior and out-of-sample stability.','基于历史数据开展 Alpha 因子与信号研究，分析因子表现和样本外稳定性。')},
 {id:'hetang',years:'2024.08 — 2024.11',title:pair('Hetang Venture Capital','荷塘创业投资管理有限公司'),role:pair('Venture Capital Analyst','风险投资分析师'),link:null,text:pair('Evaluated eight medical-device investment opportunities through founder discussions, roadshows and financial/technical analysis.','评估八个医疗器械投资项目，通过路演、团队交流与财务／技术研究支持投资筛选。')},
 {id:'guotai',years:'2024.07 — 2024.08',title:pair('Guotai Junan Securities','国泰君安证券 · 浙江分公司'),role:pair('Intern · Python data automation','实习生 · Python 数据自动化'),link:null,text:pair('Built and promoted a Python tool to retrieve and process business reports for 25 branches; researched 23 listed companies.','自主开发并推广 Python 工具，自动抓取与处理 25 家分支机构业务报告；研究 23 家上市公司。')},
 {id:'minsheng',years:'2022.06 — 2022.08',title:pair('Minsheng Securities','民生证券 · 浙江分公司'),role:pair('Financial-data intern','财务数据分析实习生'),link:null,text:pair('Analyzed and organized financial data, developing business context for later modeling and automation work.','开展财务数据分析与整理，为后续建模及自动化工作积累业务背景。')}
];
export const education = [
 {years:'2025 — 2026',title:pair('Johns Hopkins University','约翰斯·霍普金斯大学'),detail:pair('M.S. Information Systems & Artificial Intelligence · Beta Gamma Sigma','信息系统与人工智能理学硕士 · Beta Gamma Sigma'),note:pair('Degree conferred August 29, 2026','学位授予：2026 年 8 月 29 日')},
 {years:'2021 — 2025',title:pair('Hangzhou City University / University of Waikato','浙大城市学院／怀卡托大学'),detail:pair('Dual Finance degrees: Bachelor of Business & Bachelor of Economics','金融学双学位：工商管理学士、经济学学士'),note:pair('GPA 3.67/4.0 · Debate captain · Class representative','GPA 3.67/4.0 · 辩论队队长 · 学习委员')},
 {years:'2023 — 2024',title:pair('CQF Institute','CQF Institute'),detail:pair('Certificate in Quantitative Finance','量化金融分析师'),note:pair('Passed with Distinction','Passed with Distinction')}
];
export const publication = {title:'Trend Prediction Analysis of Shanghai Composite Index Based on LSTM Neural Network',author:'Gao, R.',year:2024,venue:'Highlights in Business, Economics and Management, 24, 409–416.',doi:'10.54097/qw8hwy64',url:'https://doi.org/10.54097/qw8hwy64',
 summary:pair('Time-series research under Professor Peter Kempthorne, combining LSTM modeling, volatility-penalty regularization and 2,000 Monte Carlo simulations.','在 Peter Kempthorne 教授指导下开展时间序列研究，结合 LSTM、波动率惩罚正则化与 2,000 次蒙特卡洛模拟。')};
export const honors = [pair('Kaggle Optiver · Bronze medal','Kaggle Optiver · 铜牌'),pair('WorldQuant Challenge 2024 · Gold Level','2024 WorldQuant Challenge · Gold Level'),pair('CFA Research Challenge · Outstanding Investment Research','CFA Research Challenge · 优秀投资研究奖')];
export const archiveNotes = pair('Public summaries include private projects; their repositories still require permission. Dates and scope follow the September 2026 career record.','展示内容包含私有项目，但源码仍需授权。日期与工作范围以 2026 年 9 月履历为准。');
