import {person,projects,experience,education,publication,honors,archiveNotes} from './content.js';
import {mountOrbit} from './orbit.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return localStorage.getItem(key)??fallback;}catch{return fallback;}};
const save=(key,value)=>{try{localStorage.setItem(key,value);}catch{/* Storage may be disabled. */}};
const urlLocale=new URLSearchParams(location.search).get('lang');
let lang=['en','zh'].includes(urlLocale)?urlLocale:read('rg.language',navigator.language.startsWith('zh')?'zh':'en');
if(!['en','zh'].includes(lang))lang='en';
const prefersReduce=matchMedia('(prefers-reduced-motion: reduce)');
let motion=read('rg.motion',prefersReduce.matches?'off':'on')==='on', sound=false, filter='all', cleanup=()=>{}, lastSection='#work', opener=null, audioContext=null;
const t=v=>Array.isArray(v)?v[lang==='zh'?1:0]:v;
const l=(en,zh)=>lang==='zh'?zh:en;
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.5"/></svg>';
const next='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.5"/></svg>';
const ext=(href,text,cls='')=>`<a class="${cls}" href="${escape(href)}" target="_blank" rel="noopener noreferrer">${escape(text)} ${arrow}</a>`;
const categories={all:['All work','全部项目'],agents:['Agents','智能体'],health:['Healthcare','医疗 AI'],systems:['Systems','系统'],robotics:['Robotics','机器人'],experiments:['Experiments','实验']};
const sectionHead=(number,tag,title,note)=>`<div class="section-heading reveal"><div><p class="eyebrow"><span>${number}</span> ${tag}</p><h2>${title}</h2></div>${note?`<p class="section-note">${note}</p>`:''}</div>`;
const chip=x=>`<span class="chip">${escape(x)}</span>`;
function visual(id) {
 if(id==='anima-family')return `<div class="work-art agent-art" aria-hidden="true"><div class="art-top"><span>RUNTIME / 01</span><span class="live-dot">STATEFUL</span></div><div class="agent-orbit orbit-a"></div><div class="agent-orbit orbit-b"></div><div class="agent-core"><span>α</span><small>ANIMA²</small></div><div class="node n1">MEMORY<span>recall · retain</span></div><div class="node n2">TOOLS<span>approve · execute</span></div><div class="node n3">NODES<span>delegate · return</span></div><div class="node n4">CONTEXT<span>archive · recover</span></div><div class="art-bottom"><span>CONTINUITY IS A SYSTEM PROPERTY</span><span>+ + +</span></div></div>`;
 if(id==='synapse')return `<div class="work-art bridge-art" aria-hidden="true"><div class="art-top"><span>INTERFACE / 02</span><span>ONE SCHEMA</span></div><div class="bridge-label left-label">PYTHON<small>INTELLIGENCE</small></div><div class="bridge-label right-label">RUST / C++<small>NATIVE RUNTIME</small></div><div class="bridge-line line-one"></div><div class="bridge-line line-two"></div><div class="buffer">${Array.from({length:12},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div><div class="bridge-caption">.bridge<span>shared memory</span></div><div class="art-bottom"><span>EXPLICIT TYPES. SHARED STATE.</span><span>↔</span></div></div>`;
 return `<div class="work-art health-art" aria-hidden="true"><div class="art-top"><span>FORECAST / 03</span><span>ILLUSTRATIVE TRACE</span></div><div class="health-heading">Population<span>→</span>Person</div><svg viewBox="0 0 520 220" class="forecast"><defs><linearGradient id="forecast-fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#83c4d7" stop-opacity=".2"/><stop offset="1" stop-color="#83c4d7" stop-opacity="0"/></linearGradient></defs><path class="chart-grid" d="M20 40h480M20 90h480M20 140h480M20 190h480M100 20v180M200 20v180M300 20v180M400 20v180"/><path d="M270 125 310 65 350 48 390 62 430 38 480 58 480 160 430 137 390 148 350 127 310 150Z" fill="url(#forecast-fill)"/><path class="baseline" d="M20 148Q55 80 88 116T152 106T213 135T272 117T335 104T404 102T490 113"/><path class="personal" d="M20 148Q55 80 88 116T152 106T213 135T272 117T335 87T404 103T490 111"/><path d="M270 25v175" stroke="#d1b089" stroke-dasharray="3 6" opacity=".5"/><circle cx="270" cy="117" r="5" fill="#efc48e"/></svg><div class="chart-legend"><span>● POPULATION</span><span>● PERSONAL ADAPTATION</span></div><div class="art-bottom"><span>CALIBRATE. VALIDATE. FALL BACK.</span><span>RESEARCH</span></div></div>`;
}
function feature(p,i) {
 return `<article class="featured-work reveal ${i%2?'reverse':''}" data-project-card="${p.id}"><a href="#project/${p.id}" class="art-link" aria-label="${escape(l('Read case study: ','阅读项目：')+p.name)}">${visual(p.id)}</a><div class="work-copy"><p class="eyebrow">${p.number} / ${escape(t(p.type))}</p><h3>${escape(p.name)}</h3><p class="work-headline">${escape(t(p.headline)).replace('\n','<br>')}</p><p class="work-summary">${escape(t(p.summary))}</p><div class="chips">${p.stack.map(chip).join('')}</div><div class="work-actions"><a class="text-link" href="#project/${p.id}">${l('Explore the case study','查看项目详情')} ${next}</a><span class="visibility">${p.private?l('PRIVATE · DEMO AVAILABLE','私有 · 可演示'):l('PUBLIC SOURCE','公开源码')}</span></div></div></article>`;
}
function renderIndex() {
 const subset=projects.filter(p=>filter==='all'||p.category===filter);
 $('#project-list').innerHTML=subset.map((p,i)=>`<a class="index-row" href="#project/${p.id}"><span class="index-no">${String(i+1).padStart(2,'0')}</span><div><h4>${escape(p.name)}</h4><p>${escape(t(p.summary))}</p></div><span class="index-category">${escape(t(categories[p.category]))}<small>${p.private?l('Private','私有'):l('Public','公开')}</small></span><span class="index-arrow">${arrow}</span></a>`).join('');
 $('#result-count').textContent=l(`${subset.length} projects`,`${subset.length} 个项目`);
 $$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));
}
function timelineItem(x,i) {return `<article class="timeline-item reveal ${i===0?'current':''}"><div class="time">${escape(lang==='zh'?x.years.replace('Present','至今').replace('Part-time / Remote','兼职／远程'):x.years)}</div><div class="time-point"></div><div class="timeline-body"><h3>${x.link?ext(x.link,t(x.title)):escape(t(x.title))}</h3><p class="role">${escape(t(x.role))}</p><p>${escape(t(x.text))}</p>${x.id==='cdhai'?ext(person.professor,l('Professor Gordon Gao','Gordon Gao 教授'),'inline-link'):''}</div></article>`;}
function render() {
 cleanup();
 document.documentElement.lang=lang==='zh'?'zh-CN':'en';
 document.documentElement.dataset.motion=motion?'on':'off';
 document.title=l('Rongze Gao — AI, Systems & Human Possibility','高荣泽 Rongze Gao — 智能体、医疗 AI 与系统工程');
 $('#app').innerHTML=`<div class="page-grain" aria-hidden="true"></div><div class="reading-progress" aria-hidden="true"></div>
 <header class="header"><a href="#top" class="wordmark" aria-label="Rongze Gao home">RG<span>✳</span><small>RONGZE GAO</small></a><nav id="navigation" aria-label="${l('Main navigation','主导航')}"><a href="#work">${l('Work','作品')}</a><a href="#research">${l('Research','研究')}</a><a href="#trajectory">${l('Trajectory','经历')}</a><a href="#beyond">${l('Beyond','之外')}</a></nav><div class="header-controls"><button class="icon-button search-button" data-search aria-label="${l('Search projects, Control or Command K','搜索项目，Ctrl 或 Command K')}"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><kbd>⌘ K</kbd></button><button class="language" data-language>${lang==='en'?'中文':'EN'}</button><a href="#contact" class="header-contact">${l('Let’s talk','联系我')} ${arrow}</a><button class="menu-button" data-menu aria-controls="navigation" aria-expanded="false" aria-label="${l('Toggle navigation','展开导航')}"><span></span><span></span></button></div></header>
 <main id="main"><section class="hero" id="top"><div class="hero-top"><p class="eyebrow">INDEPENDENT PORTFOLIO <span class="dash"></span> VOL. 2026</p><p class="coordinates">AI · SYSTEMS · HUMAN POSSIBILITY</p></div><div class="hero-layout"><div class="hero-copy"><div class="name-label"><span class="live-dot"></span> ${l('RESEARCHER. ENGINEER. BUILDER.','研究者。工程师。构建者。')}</div><h1><span>Rongze</span><span class="surname">Gao<span class="name-period">.</span><small>高荣泽</small></span></h1><p class="hero-statement">${l('Intelligence that','让智能')}<br><em>${l('goes beyond the screen.','走出屏幕。')}</em></p><p class="hero-intro">${l('Persistent agents. Patient-aware models. Physical systems. I turn ideas into things that can be built, tested, and used.','持续运行的智能体、理解患者的模型、连接现实的系统。把想法变成能够实现、验证和使用的事物。')}</p><div class="hero-actions"><a class="button primary" href="#work">${l('Explore my work','探索我的作品')} ${next}</a><a class="button quiet" href="#profile">${l('The person behind it','了解完整背景')} ${arrow}</a></div></div><div class="hero-observatory"><canvas id="orbit-canvas" aria-hidden="true"></canvas><div class="orbit-label label-top"><span>01 / COGNITION</span><small>${l('Memory → action','记忆 → 行动')}</small></div><div class="orbit-label label-bottom"><span>02 / CONNECTION</span><small>${l('Human ↔ machine','人与机器')}</small></div><div class="orbit-center-note">RG / FIELD 26</div><div class="orbital-coordinate">θ 0.628 / φ 1.618 <small>${l('A GENERATIVE STUDY · NOT LIVE TELEMETRY','生成式视觉实验 · 非实时遥测')}</small></div></div></div><div class="hero-bottom"><a href="#work" class="scroll-cue"><span>↓</span> ${l('SCROLL TO DISCOVER','向下探索')}</a><div class="hero-affiliations"><span>JOHNS HOPKINS</span><i>·</i><span>CDHAI</span><i>·</i><span>TUSKROBOTS</span></div><div class="motion-controls"><button data-motion aria-pressed="${motion}">${motion?'◉':'○'} ${l('Motion','动效')}</button><button data-sound aria-pressed="${sound}">${sound?'♫':'♪'} ${l('Sound','声音')} ${sound?'ON':'OFF'}</button></div></div></section>
 <div class="marquee" aria-hidden="true"><div>${Array(2).fill(`<span>PERSISTENCE</span><i>✳</i><span class="outline-word">INTELLIGENCE</span><i>✳</i><span>HUMAN POSSIBILITY</span><i>✳</i>`).join('')}</div></div>
 <section id="work" class="section work-section">${sectionHead('01',l('SELECTED SYSTEMS','精选系统'),l('Ideas, made <em>real.</em>','把想法，<em>做成系统。</em>'),l('A closer look at what I build, why I build it, and what the evidence actually supports.','不只介绍做了什么，也说明为什么做、如何实现，以及证据能支持什么。'))}<div class="featured-stack">${projects.filter(p=>p.featured).map(feature).join('')}</div>
 <div class="archive-heading reveal"><h3>${l('The project index','项目索引')}<sup>${String(projects.length).padStart(2,'0')}</sup></h3><button class="text-link" data-search>${l('Find something specific','搜索具体项目')} ${arrow}</button></div><div class="filter-bar" role="group" aria-label="${l('Filter projects','项目筛选')}">${Object.entries(categories).map(([k,v])=>`<button data-filter="${k}" aria-pressed="${filter===k}">${t(v)}</button>`).join('')}<span id="result-count" role="status"></span></div><div id="project-list"></div><p class="archive-note">${escape(t(archiveNotes))}</p></section>
 <section id="research" class="section research-section">${sectionHead('02',l('RESEARCH & METHOD','研究与方法'),l('Evidence before<br><em>eloquence.</em>','先有证据，<br><em>再有表达。</em>'),l('At Johns Hopkins, the interesting question is not just what a model can say. It is what the data and the experiment can justify.','在约翰斯·霍普金斯大学，我关注的不只是模型能说什么，更是数据和实验能够支持什么。'))}<div class="research-grid"><div class="research-manifesto reveal"><span class="cross-mark" aria-hidden="true">✳</span><p>${escape(t(person.philosophy))}</p><div class="research-links">${ext(person.lab,'CDHAI / AI Agent Lab')}${ext(person.professor,'Gordon Gao')}</div></div><a href="${publication.url}" target="_blank" rel="noopener noreferrer" class="publication reveal"><div class="pub-top"><span>PUBLICATION / 2024</span>${arrow}</div><div class="paper-art" aria-hidden="true"><span>f(t)</span><div class="paper-lines"></div><small>LSTM · TIME SERIES</small></div><h3>${escape(publication.title)}</h3><p>${escape(publication.venue)}</p><span class="doi">DOI ${publication.doi}</span></a></div><div class="honors-strip reveal">${honors.map((h,i)=>`<div><span>0${i+1}</span><p>${escape(t(h))}</p></div>`).join('')}</div></section>
 <section id="trajectory" class="section trajectory-section">${sectionHead('03',l('TRAJECTORY','经历与成长'),l('A path, not<br><em>a straight line.</em>','不是直线，<br><em>是不断延伸的路径。</em>'),l('Finance taught me to question the numbers. Engineering taught me to make the answer work.','金融训练让我审查数字，工程实践让我把答案真正做出来。'))}<div class="trajectory-layout"><aside class="trajectory-aside reveal"><p class="eyebrow">2021 — 2026</p><p>${escape(t(person.about))}</p><a href="#profile" class="text-link">${l('Read my full background','阅读完整经历')} ${arrow}</a></aside><div class="timeline">${experience.slice(0,3).map(timelineItem).join('')}<details class="earlier"><summary>${l('Earlier experience · Finance & quantitative research','早期经历 · 金融与量化研究')} <span>+</span></summary>${experience.slice(3).map(timelineItem).join('')}</details></div></div><div class="education-grid">${education.map((e,i)=>`<article class="education-item reveal"><span>${e.years}</span><h3>${escape(t(e.title))}</h3><p>${escape(t(e.detail))}</p><small>${escape(t(e.note))}</small></article>`).join('')}</div></section>
 <section id="beyond" class="section beyond-section">${sectionHead('04',l('BEYOND THE TERMINAL','终端之外'),l('Curiosity has<br><em>no off switch.</em>','好奇心，<br><em>没有关机键。</em>'),l('Flight, spatial worlds and the joy of making something move. The same instincts, outside the editor.','飞行、空间世界，以及让事物动起来的乐趣。离开编辑器，好奇心仍在继续。'))}<div class="beyond-grid"><article class="flight-card reveal"><div class="flight-art" aria-hidden="true"><div class="radar-ring r1"></div><div class="radar-ring r2"></div><div class="radar-ring r3"></div><div class="radar-sweep"></div><span class="airplane">⌁</span><span class="radar-label">PROCEDURE / PRECISION</span></div><div><p class="eyebrow">01 / FLIGHT & FPV</p><h3>${l('A different perspective.','换一个高度，看世界。')}</h3><p>${l('FAA Part 141 private-pilot training at Washington International Flight Academy. A practice in procedure, spatial judgment and responsibility—not a claim of a completed pilot certificate.','在 Washington International Flight Academy 接受 FAA Part 141 私人飞行员课程训练。练习程序、空间判断与责任；不将训练背景表述为已取得执照。')}</p></div></article><a href="/game.html" class="play-card reveal"><div class="play-grid" aria-hidden="true"></div><span class="play-orbit" aria-hidden="true">✳</span><p class="eyebrow">02 / INTERACTIVE PLAYGROUND</p><h3>${l('Less reading.<br>More playing.','少一点阅读，<br>多一点探索。')}</h3><span class="button quiet">${l('Enter the web game','进入网页游戏')} ${arrow}</span><small>${l('The original interactive game, preserved.','保留原有互动游戏。')}</small></a></div></section>
 <section id="contact" class="section contact-section"><div class="contact-kicker reveal"><p class="eyebrow">05 / WHAT COMES NEXT</p><span>${l('Ideas welcome. Thoughtful collaboration, too.','欢迎想法，也欢迎认真的合作。')}</span></div><a class="contact-title reveal" href="mailto:${person.email}">${l('Let’s build','一起构建')}<br><em>${l('something that matters.','有意义的事物。')}</em>${arrow}</a><div class="contact-bottom"><div><a class="email-link" href="mailto:${person.email}">${person.email}</a><button class="copy-button" data-copy aria-label="${l('Copy email address','复制邮箱地址')}">${l('Copy','复制')} ↗</button></div><div class="social-links">${ext(person.github,'GitHub')}${ext(person.linkedin,'LinkedIn')}<a href="https://private.rongzegao.com" target="_blank" rel="noopener noreferrer">${l('Private space','私域')} ${arrow}</a></div></div></section></main>
 <footer class="footer"><a href="#top" class="wordmark">RG<span>✳</span></a><span>© 2026 RONGZE GAO</span><span>${l('CONTENT UPDATED','内容更新')} / 2026.09</span><a href="#top">${l('BACK TO TOP','返回顶部')} ↑</a></footer>`;
 renderIndex();
 const stopOrbit=mountOrbit($('#orbit-canvas'),motion);
 const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target);}}),{threshold:.06});
 $$('.reveal').forEach(el=>io.observe(el));
 let scrollRAF=0;
 const updateProgress=()=>{scrollRAF=0;const max=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;};
 const onScroll=()=>{if(!scrollRAF)scrollRAF=requestAnimationFrame(updateProgress);};
 addEventListener('scroll',onScroll,{passive:true});updateProgress();
 const activeIO=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)$$('#navigation a').forEach(a=>a.setAttribute('aria-current',a.hash===`#${e.target.id}`?'location':'false'));}),{rootMargin:'-15% 0px -65% 0px'});
 $$('main > section[id]').forEach(e=>activeIO.observe(e));
 cleanup=()=>{stopOrbit();io.disconnect();activeIO.disconnect();removeEventListener('scroll',onScroll);cancelAnimationFrame(scrollRAF);};
}
function detailChrome(content){return `<div class="dialog-top"><a href="#top" class="wordmark" data-close>RG<span>✳</span></a><div><button class="language" data-language>${lang==='en'?'中文':'EN'}</button><button class="close-button" data-close aria-label="${l('Close detail','关闭详情')}">× <small>ESC</small></button></div></div>${content}`;}
function projectDetails(p){return detailChrome(`<article class="case-study"><p class="eyebrow">${escape(t(p.type))} / ${p.private?l('PRIVATE SOURCE','私有源码'):l('PUBLIC SOURCE','公开源码')}</p><h2 id="dialog-title">${escape(p.name)}</h2><p class="case-summary">${escape(t(p.summary))}</p><div class="case-meta"><span>${escape(t(p.status))}</span><div class="chips">${p.stack.map(chip).join('')}</div></div><section><h3>${l('01 / The problem','01 / 问题')}</h3><p>${escape(t(p.problem))}</p></section><section><h3>${l('02 / What I built','02 / 具体实现')}</h3><ul>${p.build.map(b=>`<li>${escape(t(b))}</li>`).join('')}</ul></section><section><h3>${l('03 / Verification & deliverables','03 / 验证与交付')}</h3><p>${escape(t(p.evidence))}</p></section><aside class="scope-note"><h3>${l('Scope & limitations','范围与边界')}</h3><p>${escape(t(p.boundary))}</p></aside><div class="case-links">${p.links.map(([n,u])=>ext(u,n,'button quiet')).join('')}</div>${p.private?`<p class="private-note">${l('The case study is public; source links need repository permission. A project walkthrough can be arranged directly.','案例介绍公开，源码链接仍需仓库权限。可直接联系我进行项目演示。')}</p>`:''}<button data-close class="text-link back-link">← ${l('Back to the portfolio','返回作品集')}</button></article>`);}
function profileDetails(){return detailChrome(`<article class="case-study profile-detail"><p class="eyebrow">FULL BACKGROUND / 2026.09</p><h2 id="dialog-title">${l('Rongze Gao','高荣泽')}<em>${l('A little more context.','更多关于我。')}</em></h2><p class="case-summary">${escape(t(person.about))}</p><p>${escape(t(person.philosophy))}</p><section><h3>${l('Education & credentials','教育与资格')}</h3>${education.map(x=>`<div class="profile-row"><small>${x.years}</small><h4>${escape(t(x.title))}</h4><p>${escape(t(x.detail))}</p><p>${escape(t(x.note))}</p></div>`).join('')}</section><section><h3>${l('Professional & research experience','工作与研究经历')}</h3>${experience.map(x=>`<div class="profile-row"><small>${escape(lang==='zh'?x.years.replace('Present','至今').replace('Part-time / Remote','兼职／远程'):x.years)}</small><h4>${escape(t(x.title))}</h4><p class="role">${escape(t(x.role))}</p><p>${escape(t(x.text))}</p>${x.link?ext(x.link,l('Related work','相关工作'),'inline-link'):''}</div>`).join('')}</section><section><h3>${l('Honors & publication','荣誉与发表')}</h3><ul>${honors.map(x=>`<li>${escape(t(x))}</li>`).join('')}</ul><h4>${ext(publication.url,publication.title)}</h4><p>${publication.author} (${publication.year}). ${publication.venue}</p><p>${escape(t(publication.summary))}</p></section><div class="case-links">${ext(person.professor,'Gordon Gao')}${ext(person.github,'GitHub')}${ext(person.linkedin,'LinkedIn')}</div><p class="private-note">${l('Earlier quantitative experience provides context; simulations and competition results are not represented as live investment performance. Public contact:','早期量化经历作为背景；不以模拟或竞赛结果代替真实投资业绩。公开联系方式：')} <a href="mailto:${person.email}">${person.email}</a></p><button class="text-link" data-close>← ${l('Back to portfolio','返回作品集')}</button></article>`);}
function route() {
 let hash=location.hash;try{hash=decodeURIComponent(hash);}catch{/* Ignore malformed externally supplied hash escapes. */}
 const dialog=$('#detail-dialog');
 if(hash.startsWith('#project/')) {
  const p=projects.find(x=>x.id===hash.slice(9));
  if(!p){notify(l('Project not found. Please choose from the index.','未找到该项目，请从索引选择。'));if(dialog.open)dialog.close();document.body.classList.remove('modal-open');return;}
  dialog.innerHTML=projectDetails(p); if(!dialog.open)dialog.showModal(); dialog.scrollTop=0; document.body.classList.add('modal-open');
 } else if(hash==='#profile') {dialog.innerHTML=profileDetails();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');}
 else {if(dialog.open)dialog.close();document.body.classList.remove('modal-open');lastSection=hash||'#work';}
}
function closeDetail(){const dialog=$('#detail-dialog');if(dialog.open)dialog.close();document.body.classList.remove('modal-open');if(/^https?:$/.test(location.protocol))history.replaceState(null,'',location.pathname+location.search+lastSection);else location.hash=lastSection;opener?.isConnected&&opener.focus({preventScroll:true});}
function notify(message){const n=$('#notification');n.textContent=message;n.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>n.classList.remove('show'),3200);}
function soundClick(){if(!sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.setValueAtTime(590,audioContext.currentTime);gain.gain.setValueAtTime(.025,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.06);osc.connect(gain);gain.connect(audioContext.destination);osc.start();osc.stop(audioContext.currentTime+.07);osc.onended=()=>{osc.disconnect();gain.disconnect();};}catch{sound=false;notify(l('Audio is unavailable in this browser.','当前浏览器无法启用声音。'));}}
function searchResults(query='') {
 const q=query.trim().toLowerCase();const found=projects.filter(p=>[p.name,...p.summary,...p.type,...p.stack].join(' ').toLowerCase().includes(q));
 $('#search-results').innerHTML=found.length?found.map(p=>`<a href="#project/${p.id}" data-search-result><span>${escape(p.name)}<small>${escape(t(p.type))}</small></span>${arrow}</a>`).join(''):`<p class="search-empty">${l('No matching project. Try “memory”, “Python” or “health”.','没有匹配项目，试试“记忆”“Python”或“医疗”。')}</p>`;
 $('#search-count').textContent=l(`${found.length} results`,`${found.length} 个结果`);
}
function openSearch(){const d=$('#search-dialog');d.innerHTML=`<div class="search-heading"><h2 id="search-title">${l('Find a signal.','寻找一个信号。')}</h2><button class="close-button" data-search-close aria-label="${l('Close search','关闭搜索')}">× <small>ESC</small></button></div><label for="search-input" class="sr-only">${l('Search project name, topic or technology','搜索项目名称、主题或技术')}</label><input id="search-input" placeholder="${l('Project, idea, technology…','项目、想法、技术…')}" type="search" autocomplete="off"><p id="search-count" role="status"></p><div id="search-results"></div><p class="search-tip">↑ ↓ ${l('to navigate','选择')} · ENTER ${l('to explore','打开')}</p>`;searchResults();d.showModal();$('#search-input').focus();}
async function copyEmail(){try{await navigator.clipboard.writeText(person.email);notify(l('Email address copied.','邮箱地址已复制。'));}catch{notify(`${l('Copy this address:','请复制：')} ${person.email}`);}}
document.addEventListener('click',e=>{
 const b=e.target.closest('a,button');if(!b)return;
 if(b.hasAttribute('data-sound')){sound=!sound;b.setAttribute('aria-pressed',String(sound));b.textContent=`${sound?'♫':'♪'} ${l('Sound','声音')} ${sound?'ON':'OFF'}`;soundClick();return;}
 soundClick();
 if(b.hasAttribute('data-language')){const y=scrollY;lang=lang==='en'?'zh':'en';save('rg.language',lang);const u=new URL(location.href);u.searchParams.set('lang',lang);if(/^https?:$/.test(location.protocol))history.replaceState(null,'',u);render();route();scrollTo({top:y,behavior:'instant'});return;}
 if(b.hasAttribute('data-motion')){motion=!motion;save('rg.motion',motion?'on':'off');const y=scrollY;render();scrollTo({top:y,behavior:'instant'});return;}
 if(b.hasAttribute('data-menu')){const expanded=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(expanded));$('#navigation').classList.toggle('expanded',expanded);return;}
 if(b.hasAttribute('data-filter')){filter=b.dataset.filter;renderIndex();return;}
 if(b.hasAttribute('data-close')){e.preventDefault();closeDetail();return;}
 if(b.hasAttribute('data-search')){opener=b;openSearch();return;}
 if(b.hasAttribute('data-search-close')){$('#search-dialog').close();opener?.focus();return;}
 if(b.hasAttribute('data-copy')){copyEmail();return;}
 if(b.hasAttribute('data-search-result')){$('#search-dialog').close();}
 if(b.hash?.startsWith('#project/')||b.hash==='#profile'){opener=b;if(location.hash===b.hash)route();}
 if(b.closest('#navigation')){$('#navigation').classList.remove('expanded');$('[data-menu]').setAttribute('aria-expanded','false');}
});
document.addEventListener('input',e=>{if(e.target.id==='search-input')searchResults(e.target.value);});
document.addEventListener('keydown',e=>{
 if(e.key==='Escape'&&$('#detail-dialog').open){e.preventDefault();closeDetail();return;}
 if(e.key==='Escape'&&$('#search-dialog').open){e.preventDefault();$('#search-dialog').close();opener?.isConnected&&opener.focus({preventScroll:true});return;}
 if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('#detail-dialog').open){$('#search-dialog').open?$('#search-dialog').close():openSearch();}return;}
 if($('#search-dialog').open){const results=$$('[data-search-result]');const index=results.indexOf(document.activeElement);if(e.key==='ArrowDown'&&results.length){e.preventDefault();results[(index+1)%results.length].focus();}if(e.key==='ArrowUp'&&results.length){e.preventDefault();(index<=0?$('#search-input'):results[index-1]).focus();}if(e.key==='Enter'&&document.activeElement.id==='search-input'&&results.length){e.preventDefault();results[0].click();}}
 if(e.key==='Escape'){$('#navigation')?.classList.remove('expanded');$('[data-menu]')?.setAttribute('aria-expanded','false');}
});
$('#detail-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});
$('#detail-dialog').addEventListener('click',e=>{if(e.target===$('#detail-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail();}});
$('#search-dialog').addEventListener('click',e=>{if(e.target===$('#search-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
addEventListener('hashchange',route);
prefersReduce.addEventListener('change',e=>{motion=!e.matches;render();route();});
addEventListener('pagehide',()=>{cleanup();audioContext?.close();});
addEventListener('pageshow',e=>{if(e.persisted){audioContext=null;render();route();}});
render();route();
